### ISSUE TITLE
Generate sitemap from app or router

### ISSUE THREAD

**Issue by morenoh149** [ekalinin/sitemap.js#21]
Nice module!
I was wondering if there was a way to pass in an express object, or express router object to sitemap.js and have it spit out the sitemap.xml file.

**Comment by chovy** [comment]
while this isn't my module, what I do is generate the sitemap.xml daily via cronjob and just write it out to a static directory.

**Comment by ekalinin** [comment]
@chovy :+1:
@morenoh149 Do you want to have an ability to generate all available endpoints by getting express router object? And then put them into sitemap.js?

**Comment by morenoh149** [comment]
@ekalinin pretty much. I looked at bit at the express objects but couldn't find an obvious way to get this data out of it

**Comment by loganknecht** [comment]
Just wondering, is this something that you are intending to resolve? It is a requirement that I would like to request as well.

Even more so, what would be cool is if there was an option so that each router is spit out into its own sub-xml file. Then these are children of some root xml file, so that way it can scale with crazy large sites.

**Comment by morenoh149** [comment]
A solution @berkeleyTrue came up with was this
```javascript
var keystone = require('keystone'),
    moment = require('moment');

module.exports = function(app) {
  var Post = keystone.list('Post');

  app.get('/sitemap.xml', function(req, res, next) {
    var now = moment().format('YYYY-MM-DD'),
        siteUrl = 'http://www.r3dm.com';

    Post
      .model
      .find()
      .where({ state: 'published' })
      .where('content').ne(null)
      .select('slug')
      .exec()
      .then(function(posts) {
        res.header('Content-Type', 'application/xml');
        res.render('sitemap', {
          now: now,
          siteUrl: siteUrl,
          posts: posts
        });
      }, next);
  });
};
```
Serves us well.

**Comment by chovy** [comment]
This depends on the size of your db and how long that query would take. I
personally think its better to generate the sitemap.xml statically from a
cronjob at 2am rather than whenever it is requested.

On Tue, Feb 17, 2015 at 3:00 PM, Harry Moreno <notifications@github.com>
wrote:

> A solution @berkeleyTrue <https://github.com/berkeleyTrue> came up with
> was this
>
> var keystone = require('keystone'),
>     moment = require('moment');
> module.exports = function(app) {
>   var Post = keystone.list('Post');
>
>   app.get('/sitemap.xml', function(req, res, next) {
>     var now = moment().format('YYYY-MM-DD'),
>         siteUrl = 'http://www.r3dm.com';
>
>     Post
>       .model
>       .find()
>       .where({ state: 'published' })
>       .where('content').ne(null)
>       .select('slug')
>       .exec()
>       .then(function(posts) {
>         res.header('Content-Type', 'application/xml');
>         res.render('sitemap', {
>           now: now,
>           siteUrl: siteUrl,
>           posts: posts
>         });
>       }, next);
>   });
> };
>
> Serves us well.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ekalinin/sitemap.js/issues/21#issuecomment-74774097>.
>



-- 
Anthony Ettinger
http://about.me/anthony.ettinger

**Comment by morenoh149** [comment]
Indeed this would not be good for a high traffic site.

**Comment by ekalinin** [comment]
The solution was found.
