### ISSUE TITLE
Module '"zlib"' has no exported member 'CompressCallback'

### ISSUE THREAD

**Issue by ludovit-ubrezi** [ekalinin/sitemap.js#221]
Hi at version node -v v10.11.0 it has this nasty bug. 

✖ ｢atl｣: Checking finished with 1 errors
[at-loader] ./node_modules/sitemap/dist/lib/sitemap.d.ts:11:10 
    TS2305: Module '"zlib"' has no exported member 'CompressCallback'.

![image](https://user-images.githubusercontent.com/29823609/62703063-967f7f00-b9e8-11e9-9dc9-d98eb4475cac.png)

**Comment by derduher** [comment]
@ludovit-ubrezi I think I spotted the issue. I wasn't including node's typedef. Can you try again this time with master?

**Comment by mooyoul** [comment]
Hello @derduher, This issue is still not resolved even you moved @types/node dependency from dev dependencies from dependencies. I think Typescript compiler choices project's @types/node dependency instead of reading package's own @type/node dependency.

You can reproduce this issue by installing sitemap with old @types/node dependency.

Since i'm using Sitemap package in AWS Lambda environment (Node.js 8.10 runtime), My project uses `@types/node@8` as dependency. To resolve this issue from project side, I declared following module declaration: 

```typescript
declare module "zlib" {
  // @ts-ignore
  type CompressCallback = (error: Error | null, result: Buffer) => void;
}
```

**Comment by derduher** [comment]
@mooyoul Since this only happens with typescript users on Node 8 AND we're a couple months from the end of LTS for Node 8, I'm probably not going to open a PR for this one myself. You are welcome to open one yourself though, I'm just not sure how to support multiple typescript declarations of node.

**Comment by Chocobozzz** [comment]
> I think Typescript compiler choices project's @types/node dependency instead of reading package's own @type/node dependency.

You have to add the sitemap `@types` in `typeRoots` if you defined it:

```
"typeRoots": [
  "node_modules/sitemap/node_modules/@types",
  ...
],
```

FYI I had this issue using node 10 typings (maybe `CompressCallback` was added in node 12?)
