### ISSUE TITLE
createSitemapsAndIndex not on streams?

### ISSUE THREAD

**Issue by bdrtsky** [ekalinin/sitemap.js#262]
I see huge changes, congrats. Streams everywhere!

But what about createSitemapsAndIndex? I have 20kk pages. ican't load them at once, since they don't even fit in my RAM. I was hoping to use streams to generate sitemaps and index.

**Comment by derduher** [comment]
@bdrtsky Its being actively worked on by a contributor. Feel free to chime in #258. The short story is that it is the most difficult thing to do correctly so rather than hold up the rest of the code, it was carved off.
For what its worth though I think you'll be happy with memory consumption. As that went down from > 1gb to ~70mb for 20k urls
