### ISSUE TITLE
Compatibility with Next.js

### ISSUE THREAD

**Issue by markjackson02** [ekalinin/sitemap.js#276]
Should this package work with Next.js? 

When I try to import sitemap.js package into my Next.js server-rendered page (sitemap.xml.js):

```
import { SitemapStream } from 'sitemap';
```

I get this error at compile time:
```
[ event ] build page: /sitemap.xml
[ wait ]  compiling ...
[ error ] ../node_modules/sitemap/dist/lib/xmllint.js
Module not found: Can't resolve 'child_process' in 'C:\workspace\myapp\node_modules\sitemap\dist\lib'
```

**Comment by derduher** [comment]
I think Next is trying to build a browser version of this module which is not supported. Because the browser doesn't consume sitemaps crawlers do and they expect a xml file on request not js that builds a html representation of a xml file.

I do think I remember seeing an older version of this library included in a nextjs extension when browsing through folks that depend on this library. You might try looking for an adapter like that. It would have to only execute on request to the server,

**Comment by markjackson02** [comment]
Thanks @derduher 

I found this package https://www.npmjs.com/package/nextjs-sitemap-generator but it is designed to only run once when the server is initialized. I want it to be dynamic based on new dynamic routes that may have been created. I just rolled my own XML build based on this general logic https://gist.github.com/fredrikbergqvist/d2896af6563b38c3d880c0e135925ad1 which seems like a good approach. Basically on my `sitemap.xml.js` page I generate the XML dynamically so it is always up to date.
