### ISSUE TITLE
SitemapIndex can only be used if you want to write it as a file

### ISSUE THREAD

**Issue by irvingswiftj** [ekalinin/sitemap.js#34]
Surely `createSitemapIndex()` should work like `createSitemap()`? Instead I find that I'm having to write a file and then read it! Thus I'm not using this module to generate my sitemap index any more.

If I get a chance, would you mind if I did a PR to implement functionality so that I can use `createSitemapIndex(conf).toString()` ?

**Comment by R3VoLuT1OneR** [comment]
`createSitemapIndex(conf).toString()` will brake backward compatibility, because I use it for writing files and others use this as well.

I can suggest to move `Sitemap` and `SitemapIndex` classes to different files, so usage of them will be something like `require('sitemap/item')` and `require('sitemap/index')`. So then we can refactor `createSitemapIndex` to something like:

```javascript
var SitemapIndex = require('sitemap/index');

function createSitemapIndex(conf) {
   return (new SitemapIndex(options)).toString();
}
```

**Comment by niftylettuce** [comment]
This feature isn't even documented...  Please document it.

**Comment by wmcmurray** [comment]
+1
I would like to handle SitemapIndex as string outputs, not as automatically written files.
@irvingswiftj Which module did you used instead ?

**Comment by irvingswiftj** [comment]
I'm afraid it was for a project in which I no longer have access to the source so i can't find out and I can't remember from the top of my head.

**Comment by rauberdaniel** [comment]
I just opened #81 which will allow to build a sitemap index and return it as string. However, this method is called `.buildSitemapIndex()` to prevent backwards compatibility. Haven’t yet documented it but will do so.

**Comment by ekalinin** [comment]
#81 merged
