### ISSUE TITLE
[ BUG ] invalid examples for new SitemapAndIndexStream

### ISSUE THREAD

**Issue by coolswood** [ekalinin/sitemap.js#357]
I get warnings from typescript that the current getSitemapStream contract is deprecated.
<img width="667" alt="Снимок экрана 2021-04-15 в 16 03 43" src="https://user-images.githubusercontent.com/25247802/114873662-30c1d800-9e04-11eb-8d11-e0964583d1ec.png">
In all the examples, two arguments in the array are returned, and the new contract requires 3.
<img width="685" alt="Снимок экрана 2021-04-15 в 16 05 40" src="https://user-images.githubusercontent.com/25247802/114873938-7bdbeb00-9e04-11eb-8160-bfbd8213e93c.png">

**Comment by coolswood** [comment]
@derduher Still no change in the examples, it is not clear what the third WriteStream argument is

**Comment by fr1sk** [comment]
@derduher why is this one closed, in readme still no `WriteStream` argument 🤔

**Comment by derduher** [comment]
@fr1sk It's been a bit so forgive me if I don't recall correctly. It looks like https://github.com/ekalinin/sitemap.js/blob/master/api.md#sitemapandindexstream has an example 
```
const ws = sitemapStream
      .pipe(createGzip()) // compress the output of the sitemap
      .pipe(createWriteStream(resolve(path + '.gz'))); // write it to sitemap-NUMBER.xml
```
Sitemap stream is where its reading from and writestream is where you want it to write to.
Basically its come to a point where it needs to swap the files its writing to because the current one has gotten too big. You need to provide it with that stream to write to.

I'll try to get back into this project this weekend. I've neglected it too long.
