### ISSUE TITLE
[question] Should urlset protocols use https instead of http ? 

### ISSUE THREAD

**Issue by emmurillo** [ekalinin/sitemap.js#358]
This got implemented by https://github.com/ekalinin/sitemap.js/issues/164 , is there a reason is back to http again ?

```
      xmlns: {
        news: false,
        xhtml: false,
        image: false,
        video: false,
        custom: ['xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"', 'xmlns:xhtml="https://www.w3.org/1999/xhtml"', 'xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"', 'xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"']
      }
```

helps modify specific protocols but not xmlns that remains http

**Comment by derduher** [comment]
namespaces are identifiers, you should not change them to https. When google or other parsers are looking at it they expect http not https. They look like urls they are not urls.

**Comment by feedm3** [comment]
I just run into the problem that Chrome doesn't render our Sitemap correctly anymore. Doing some research I ended up finding the error: If we use `xmlns:xhtml="http://www.w3.org/1999/xhtml"` the page rendering is broken.

<img width="2645" alt="Screenshot 2021-09-20 at 08 56 56" src="https://user-images.githubusercontent.com/7814926/133965872-f0a05474-1ab9-4dd5-b486-8f8c565a0b02.png">

When changing this particular link to `https` Chrome renders the XML correct:

<img width="2526" alt="Screenshot 2021-09-20 at 08 58 08" src="https://user-images.githubusercontent.com/7814926/133965998-7cf03203-298b-45a8-83dd-f7f69003d6b3.png">

I'm not sure if this is a bug in Chrome. 
- Looking at the documentation, they are using `http` everywhere: https://developers.google.com/search/docs/advanced/crawling/localized-versions#sitemap
- Also any sitemap validator I tried online tells me that the sitemap is correct with `http`:
https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fsatellytescommain-featmultilingualsitemap.gtsb.io%2Fsitemap%2Fsitemap-0.xml&submit=Validate+Sitemap

<img width="795" alt="Screenshot 2021-09-20 at 09 01 14" src="https://user-images.githubusercontent.com/7814926/133966253-c1936317-7308-4925-85c4-115d7e53a5bb.png">

- On the other hand, Firefox behaves the same. Which is an indicator for me that `https` is correct.

We decided to stick with `http` as we want to align with the documentation instead of having a nice browser rendering.
