### ISSUE TITLE
[Feature] Allow to merge streams with objectMode=true

### ISSUE THREAD

**Issue by bohdan-shulha** [ekalinin/sitemap.js#366]
**Is your feature request related to a problem? Please describe.**
I'm having multiple Readers that inspect my database and produce urls for pages on my website. They all use `objectMode=true`  option. However, when I try to `mergeStreams` of that Readers I'm getting an error.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at PassThrough.Writable.write (internal/streams/writable.js:285:13)
    at BaseStream.ondata (internal/streams/readable.js:719:22)
    at BaseStream.emit (events.js:315:20)
    at BaseStream.EventEmitter.emit (domain.js:467:12)
    at BaseStream.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
```

**Describe the solution you'd like**
Allow to pass options to `mergeStreams` so that one can specify `objectMode` for the [PassThrough constructor](https://github.com/ekalinin/sitemap.js/blob/master/lib/utils.ts#L255).

**Simplified Demo**

```
class R1 extends Readable {
  constructor() {
    super({ objectMode: true })
  }

  _read() {
    this.push({ url: 'https://my.url/' });
    this.push(null);
  }
}

class R2 extends Readable {
  constructor() {
    super({ objectMode: true })
  }

  _read() {
    this.push({ url: 'https://my.url/2' });
    this.push(null);
  }
}

simpleSitemapAndIndex({
  sourceData: mergeStreams([new R1(), new R2()]),
})
```

**Comment by huntharo** [comment]
@bohdan-shulha - I've submitted #372 that implements the suggested change.  I'd like to say thanks for pointing me in the right direction on this.  I was trying to use `mergeStreams` two merge two input streams as you showed and it hadn't dawned on me that the problem was simply that objectMode could not be set on the `PassThrough` stream.  With your tip I was able to get this working for my own needs.

The `mergeStreams` function has nothing specific to `sitemap.js` (and, if I'm reading correctly, has zero references or usages in this repo), so you can copy the 5 lines of code from this PR into your app if you want to test the change before it's merged.

**Comment by bohdan-shulha** [comment]
Thanks @huntharo , I already copied them and adjusted for my needs. And I simply forgotten that I filed an issue for this :)
