### ISSUE TITLE
Lastmod for sitemap index entries?

### ISSUE THREAD

**Issue by seanohollaren** [ekalinin/sitemap.js#91]
Is it possible to add a `lastmod` property for entries in a sitemap index?  

I currently have code like this to create the sitemap index XML string:
```javascript
// create the xml to be used for the sitemap-index by giving it an array of urls
const sitemapIndexXML = pd.xml(sitemap.buildSitemapIndex({
  urls: fileNameArray.map((fileName) => `${baseUrl}/${fileName}`)
}));
```

Is there any way get the generated sitemap index to have a `<lastmod>` element, similar to how the module allows you to pass a `lastmodISO` property when creating a sitemap?

Ideally it would produce XML like this:
```xml
<sitemap>
  <loc>http://example.com/sitemap-us.xml</loc>
  <lastmod>2016-11-22T18:06:38.207Z</lastmod>
</sitemap>
<sitemap>
  <loc>http://example.com/sitemap-ca.xml</loc>
  <lastmod>2016-11-22T18:06:38.207Z</lastmod>
</sitemap>
```

**Comment by jyotman** [comment]
@ekalinin can we introduce this feature?

According to [sitemaps protocal](https://www.sitemaps.org/protocol.html#index) there's an optional `lastmod` attribute which can be given to each sitemap in a sitemap index.

**lastmod**
> Identifies the time that the corresponding Sitemap file was modified. It does not correspond to the time that any of the pages listed in that Sitemap were changed. The value for the lastmod tag should be in W3C Datetime format.
By providing the last modification timestamp, you enable search engine crawlers to retrieve only a subset of the Sitemaps in the index i.e. a crawler may only retrieve Sitemaps that were modified since a certain date. This incremental Sitemap fetching mechanism allows for the rapid discovery of new URLs on very large sites.

**Comment by derduher** [comment]
This is supported now, sitemap.buildSitemapIndex({urls:[{url: 'http...', lastmod: '2016-11-22T18:06:38.207Z'}]})

**Comment by seanohollaren** [comment]
Awesome, thanks for the update!

**Comment by gokhancetiner** [comment]
Hello @derduher ,
 
I have a huge list I am using SitemapAndIndexStream method in sitemapAndIndex.js example but I couldn't achieve how to put lastmod property inside sitemap-index.xml.gz. How can I make it ?

Best Regards,

**Comment by derduher** [comment]
@gokhancetiner in the [getSitemapStream function](https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap-simple.ts#L54) provided to SitemapAndIndexStream, you can return an [indexItem](https://github.com/ekalinin/sitemap.js/blob/master/lib/types.ts#L311) instead of a string. This should write out the last mod date that you provide

**Comment by gokhancetiner** [comment]
Many Thanks @derduher
